Print("ABS "..Abs(-5))
Print("Min "..Min(0,10))
Print("Max "..Max(0,10))
Print("Sqrt " ..Sqrt(16))
Print("Log "..Log(6,6))
Print("Log "..Log(2,16))
Print("Div "..Div(5,0))
Print("Div "..Div(5,2))
Print(Pi)
Print(E)
Print(Log2E)
Print(GamePath)